- name: Template Kibana config
  loop:
    - src: kibana/kibana.yml
      dest: "{{ kibana.prefix.config }}/kibana.yml"
  loop_control:
    label: "{{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: Restart Kibana

- name: Start Kibana
  service:
    name: kibana
    state: started
  register: kibana_service_start_result
