---
- name: Display an error about missing kibana_system password
  when: not elasticsearch.users.builtin.kibana_system.password
  ansible.builtin.fail:
    msg: >-
      [ERROR]: The password for built-in user 'kibana_system' is not defined.
      Starting with ElasticSearch 8, security is enabled by default,
      which means that the built-in users must be password-protected.
      Please set the variable `elasticsearch.users.builtin.kibana_system.password`
      to your desired password.

- name: Check if the password for the kibana_system user is already defined
  changed_when: kibana_system_password_already_set.status == 401
  failed_when: kibana_system_password_already_set is failed and kibana_system_password_already_set.status != 401
  register: kibana_system_password_already_set
  ansible.builtin.uri:
    url: http://localhost:9200
    user: kibana_system
    password: "{{ elasticsearch.users.builtin.kibana_system.password }}"
    force_basic_auth: yes

- name: Define a password for the kibana_password user
  when: kibana_system_password_already_set is changed
  changed_when: yes
  ansible.builtin.shell:
    cmd: >-
      printf "{{ elasticsearch.users.builtin.kibana_system.password }}\n{{ elasticsearch.users.builtin.kibana_system.password }}" |
      {% for key, value in (es_env | default({})).items() %}
      {{ key }}={{ value | quote }}
      {% endfor %}
      {{ elasticsearch.prefix.bin }}/elasticsearch-reset-password -b -u kibana_system -i
